### ISSUE TITLE
Tutorial: tracing code

### ISSUE THREAD

**Issue by tenebrius1** [AY2122S1-CS2103T-T17-2/tp#1]
![image](https://user-images.githubusercontent.com/57551677/133536206-9e9364dc-d2f7-4d38-a311-9f27cf608d09.png)

Found this while looking through the developer guide, might be helpful since y'all want to implement something similar to them where you search first then delete according to the searched list. Pretty sure this is how they did it.

![image](https://user-images.githubusercontent.com/57551677/133537823-9d9b84a1-b1a9-42b6-a69a-29b36c6e8cc1.png)

Oh hey they have an entire section teaching you how to do redo/undo LOL. You should have just referenced this @knotstoks when doing the undo for your iP HAHHA

**Comment by Lemonsr** [comment]
Yup same thoughts when I saw the Undo/Redo feature LOL. 
<p align="center">
  <img src="https://user-images.githubusercontent.com/46766154/133661523-a4be9b40-f68f-4d34-b2ff-f568969c19d4.png" width="60%">
</p>
This could be a useful structure for the Tags implementation~~<br/>
The diagrams are very helpful but also a little complicated, so it'll be useful if we frequently refer back to the [design](https://nus-cs2103-ay2122s1.github.io/tp/DeveloperGuide.html#design) portion of the Dev guide.

**Comment by zihaooo9** [comment]
Wow seems pretty useful for our tP!! LGTM 😄
