### ISSUE TITLE
[PE-D] Handling extra parameters - returns an error instead of accepting the last paramter

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T17-2/tp#181]
The UG mentions that "If a parameter is expected only once in the command but you specified it multiple times, only the last occurrence of the parameter will be taken." However, the app returns an error message instead if I enter this (multiple occurrences of the qualification parameter):
![Screen Shot 2021-10-29 at 11.19.31 PM.png](https://raw.githubusercontent.com/aakanshanarain/ped/main/files/92ad45ec-17ae-47f7-8bfa-2d4ef877746c.png)

Similarly with the remarks parameter:

![Screen Shot 2021-10-29 at 11.23.08 PM.png](https://raw.githubusercontent.com/aakanshanarain/ped/main/files/e1816973-714b-4abd-b4de-d8262172eb73.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: aakanshanarain/ped#11

**Comment by zihaooo9** [comment]
The user did not put tags, hence an error was thrown. Kindly read our UG properly for further details
